reports:
  - name: "war-art"
    search: "war"
    fields: ["id", "title", "artist_title, date_display"]
    max_items: 25
    recipients: ["team@example.com"]

  - name: "peace-art"
    search: "peace"
    fields: ["id", "title", "artist_title, date_display"]
    max_items: 25
    recipients: ["team@example.com"]

  - name: "dogs"
    search: "dogs"
    fields: ["id", "title", "artist_title, date_display"]
    max_items: 25
    recipients: ["team@example.com"]
